const app=document.querySelector('#app'),status=document.querySelector('#status'),toast=document.createElement('div');toast.className='toast';document.body.appendChild(toast);
const saved=JSON.parse(localStorage.getItem('wv_comments')||'null');const comments=saved||['','','','',''];
function note(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
function home(){app.innerHTML=`<div class="wrap"><div class="hero"><h1>Connect your real Weverse account 💜</h1><p class="muted">This version contains no fake BTS post, fake people, fake likes, or pre-selected targets.</p></div><div class="card login"><div class="heart">♥</div><h2>Weverse connection required</h2><p class="muted">Sign in through the official Weverse account system. This site does not ask you to type your Weverse password into the dashboard.</p><div class="notice"><b>Important:</b> the current public Weverse materials I could verify do not provide a public OAuth/API contract for an independent website to read your live community feed and post replies on your behalf. Therefore this starter will not pretend it is connected.</div><a class="btn" href="https://account.weverse.io/login" target="_blank" rel="noopener">Open Official Weverse Login ↗</a><button class="btn secondary full" onclick="note('Signing in on Weverse does not automatically authorize this separate site.')">Why no automatic connection?</button></div></div>`}
function commentsView(){app.innerHTML=`<div class="wrap"><div class="hero"><h1>Your 5 Comment Options</h1><p class="muted">You enter all five yourself. Nothing is pre-filled.</p></div><div class="card"><div class="fields">${comments.map((c,i)=>`<div class="template"><span class="num">${i+1}</span><textarea id="c${i}" rows="2" placeholder="Enter your comment option ${i+1}...">${esc(c)}</textarea></div>`).join('')}</div><button class="btn full" id="save">Save My 5 Options</button></div></div>`;document.querySelector('#save').onclick=()=>{for(let i=0;i<5;i++)comments[i]=document.querySelector('#c'+i).value;localStorage.setItem('wv_comments',JSON.stringify(comments));note('Your five comments were saved.');}}
function targetsView(){app.innerHTML=`<div class="wrap"><h1>Targets</h1><p class="muted">Real people/comments must come from a legitimate live Weverse connection.</p><div class="card empty">No people are loaded yet.<br><br>There are deliberately no fake users in this version.</div></div>`}
function scheduleView(){app.innerHTML=`<div class="wrap"><h1>Schedule</h1><p class="muted">Timing controls are ready, but live posting requires an authorized Weverse integration.</p><div class="card"><div class="two"><div class="field"><label>Start</label><input type="datetime-local"></div><div class="field"><label>Stop</label><input type="datetime-local"></div></div><label class="muted"><input type="checkbox" checked> Require confirmation before a live action</label><button class="btn full" onclick="note('Schedule saved locally.')">Save Schedule</button></div></div>`}
function activityView(){app.innerHTML=`<div class="wrap"><h1>Activity</h1><p class="muted">Only genuine integration events should appear here.</p><div class="card empty">No live activity yet.</div></div>`}
function settingsView(){app.innerHTML=`<div class="wrap"><h1>Settings</h1><div class="card"><h3>Weverse Account</h3><p class="muted">Status: <b style="color:#ffb45d">Not connected</b></p><a class="btn" href="https://account.weverse.io/login" target="_blank" rel="noopener">Open Official Weverse Login ↗</a><p class="muted">Do not enter your password into this site. A genuine live connection needs an officially supported authorization mechanism.</p></div></div>`}
function esc(s){return String(s).replace(/[&<>]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]))}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>({home,comments:commentsView,targets:targetsView,schedule:scheduleView,activity:activityView,settings:settingsView}[b.dataset.view])());
document.querySelector('#menu').onclick=()=>document.querySelector('aside').classList.toggle('open');home();